export const FETCH_USER_INFO = 'FETCH_USER_INFO';

export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';

// 获取首页banner
export const FETCH_HOME_BANNER = 'FETCH_HOME_BANNER';

export const FETCH_HOME_HOTSTOCK = 'FETCH_HOME_HOTSTOCK';
export const FETCHING_HOME_HOTSTOCK = 'FETCHING_HOME_HOTSTOCK';

// 策略

export const STRATEGY_TAB_INDEX = 'STRATEGY_TAB_INDEX';